### PR TITLE
Solved issue#359

### LINKED ISSUE #359: add a reading progress bar to the page

### PR DESCRIPTION
**Pull request by shivhek25**
Fixes #359 

Changes proposed in this pull request:
-Updated personal scores. 
-Added reading progress bar.

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@shivhek25 provide live link

**Comment by shivhek25** [comment]
https://shivhek25.github.io/OpenCode-Collaborative/
@Anupam-dagar

**Comment by Anupam-dagar** [comment]
LGTM 👍 
what say @pradeepgangwar ?

**Comment by pradeepgangwar** [comment]
@Anupam-dagar progress bar fills up before we scroll to bottom. Is this the case with you also?

**Comment by shivhek25** [comment]
@pradeepgangwar That's because either the participant cards or the project cards haven't loaded. Was happening with me too initially. In another case where only one of themes loaded, the progress bar fell short of getting filled. If all the data is loaded, the progress bar works perfectly.

**Comment by shivhek25** [comment]
screen shot 2018-02-03 at 2 10 47 pm

As you can see here, we have almost come to the end of the file and some of the portion is yet to be filled in the progress bar. @pradeepgangwar

**Comment by pradeepgangwar** [comment]
@Anupam-dagar Please check.

**Comment by shivhek25** [comment]
Is it alright ? @Anupam-dagar

**Comment by Anupam-dagar** [comment]
LGTM

**Pull request merged**
