### PR TITLE
Fix Issue #127. Fix Mobile view for grid.

### LINKED ISSUE #127: fix mobile view for grid
grid is not centered in mobile view.
screenshot from 2018-01-11 13-31-53
Comment on issue #31 along witht the screenshot to get your marks verified. :smile:

### PR DESCRIPTION
**Pull request by Ace-Bansal**
[link](https://ace-bansal.github.io/OpenCode-Collaborative/)

close #127

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
Next time mention issue in description not in title of PR.

**Comment by pradeepgangwar** [comment]
screenshot from 2018-01-12 00-54-03

If that's your fix. I am gonna down vote this. Please make them at center.

**Comment by Ace-Bansal** [comment]
@pradeepgangwar it was in the centre when i viewed it by minimising my browser window. I'll fix it.

**Comment by Anupam-dagar** [comment]
@Ace-Bansal it's still not responsive, i can see you are using px values to make them center, this only fix it for your screen, either change the unit to vh or em or find another way.I think margin should do it.

**Comment by Ace-Bansal** [comment]
@Anupam-dagar I saw your comment after committing the changes. I've still worked in px units. Please have a look, I'll change it if it it's still not working.

**Comment by Anupam-dagar** [comment]
image
it's still the same

**Comment by Ace-Bansal** [comment]
screenshot 24

Margin auto didn't work. So I fixed it using vh values.

**Comment by aswinzz** [comment]
@Ace-Bansal  it is still not responsive. Make sure that it is responsive in all sizes.

**Comment by nikki1016** [comment]
can I fix this issue #127

**Comment by Ace-Bansal** [comment]
I've reduced the max-width to 300px because I guess mobile screens aren't really smaller than that. Please have a look.

**Comment by pradeepgangwar** [comment]
@Ace-Bansal Looks fine to me in mobile view. I think we can merge this now. We will post some issues again if minor errors are there. Good work :+:

**Pull request merged**
