### PR TITLE
Made Games open in popup

### LINKED ISSUE #360: Make Games appear as a pop up screen inside the webiste
You can use something like Iframe or whatever you like

### PR DESCRIPTION
**Pull request by AK-007**
Fixes #360

Changes proposed in this pull request:
- Games will openup in popup
- Used Colorbox OpenSource jQuery Lightbox

### CODE REVIEW

**Comment by AK-007** [comment]
@gauthamzz Plz review

**Comment by gauthamzz** [comment]
Live link

**Comment by AK-007** [comment]
Link : https://ak-007.github.io/OpenCode-Collaborative/

**Comment by gauthamzz** [comment]
1. there is no button to close it
2. It seems very slower than normal window pop up .

**Comment by AK-007** [comment]
@gauthamzz I have added the close button.
I have no idea why the game is slower.

**Comment by gauthamzz** [comment]
try using an iframe instead of jquery

**Comment by gauthamzz** [comment]
@pradeepgangwar The speed is what worries me of the game.

**Comment by Anupam-dagar** [comment]
@AK-007 games are lagging

**Comment by Anupam-dagar** [comment]
use ajax, that should do the work

**Comment by AK-007** [comment]
Even after using ajax the games are lagging.

**Comment by gauthamzz** [comment]
its okay,will merge it. add a button on the box to view in a new page. and put the close button also on the top right corner . 
fix merge conflicts and codacy errors and send pr

**Comment by AK-007** [comment]
Making a new PR

**Pull request closed without merging**
