### PR TITLE
Nityananda Gohain added in contestants

### PR DESCRIPTION
**Pull request by nityanandagohain**
Added myself as a contestant

### CODE REVIEW

**Comment by HariMahi** [comment]
how to add images to a pr like this

**Comment by nityanandagohain** [comment]
paste your photo in the contestant folder .

**Comment by HariMahi** [comment]
how to paste, please elaborate


On Wed, Jan 10, 2018 at 7:57 PM, Nityananda Gohain <notifications@github.com

**Comment by nityanandagohain** [comment]
@HariMahi Download your pic from git-hub or facebook and copy it (directly copy if you have saved it in your pc) and go to the contestant folder then paste it.

**Comment by HariMahi** [comment]
i tried it but cant copy it directly in the contestant folder

On Wed, Jan 10, 2018 at 8:34 PM, Nityananda Gohain <notifications@github.com

**Comment by nityanandagohain** [comment]
What error are you getting in your file explorer

**Pull request merged**
