### PR TITLE
Fixed issue#423

### LINKED ISSUE #423: Fix scores.json file

### PR DESCRIPTION
**Pull request by shivhek25**
Fixes #423

### CODE REVIEW

**Comment by shivhek25** [comment]
The live link is based on the master branch while the changes are made in the "fix_scores" branch and so the changes don't reflect there.

**Comment by gauthamzz** [comment]
Then provide us somethign like screenshot . and resolve the conflicts

**Comment by shivhek25** [comment]
@gauthamzz I have bettered the formatting and checked the validity of the JSON file on https://jsonlint.com/. It is showing to be valid. But the problem is that whenever I run the file locally, only user 'ashish4321' is shown on the leaderboard.

**Comment by gauthamzz** [comment]
I know what the problem is , the issue was to fix it 😂

**Comment by shivhek25** [comment]
I know ;P. The thing is that I found that user 'ashish4321' had reused some "scores:" part in his code so I omitted that part and there were some redundant user profile scores', so I removed those. I hoped that would work but it didn't. Maybe I am missing something out.

**Comment by shivhek25** [comment]
Unable to solve the issue. Closing pull request.

**Pull request closed without merging**
