### PR TITLE
updated scores.json

### PR DESCRIPTION
**Pull request by rahulkumaran**
Fixes #

Changes proposed in this pull request: updated my scores on scores.json
-

### CODE REVIEW

**Comment by rahulkumaran** [comment]
@Anupam-dagar, I guess there's been a mistake! The score got changed from 1520 to 1340!
The variation in the points is cuz of the pro designer social issue! It was said in the comments that extra points would be awarded for sharing on more social media platforms! And I shared my 6 designs on 5 social media platforms! So it should be 300 right? But I guess you've awarded only 120? Could I know the reason?

**Comment by Anupam-dagar** [comment]
@rahulkumaran , on reviewing, prodesigner one was posted as stories, stories were there only for the today's final tshirt post.Stories are also temporary.Coming to other 6 platform for stories one, fb post doesn't qualify for that and same with linkedin.Also we will be reviewing each participant by their each entry.So the points can go down for others too.

**Comment by rahulkumaran** [comment]
Also, i guess the last part where my score was 180 for the photo sharing thing on social media platforms, it got reduced to 120! I posted it on 6 platforms actually! Linkedin, fb, insta, snapchat, whatsapp and Twitter! And it said 30 for each platform n So it should be 180 only right?

**Comment by rahulkumaran** [comment]
@Anupam-dagar, the pro designer one said social media so doesn't it include Insta, snapchat, fb and Twitter? And i had to post it as stories on Insta and snapchat didn't have any other option :P
And the last part is fine! But im kinda still not satisfied with the part where my score reduced from 300 to 120 for the pro designer social thing! Cuz I guess social should consider insta, fb, twitter, snapchat and whatsapp! It wasn't specified in the issue right?

**Comment by Anupam-dagar** [comment]
see we have to keep a max limit on these issues which can float a lot of points, other people's points will also be reduced if found out.This happened last year too.That's why there is a delay in declaring the results.
Coming to final 6 one,there were two fb posts, fb story is counted and twitter post is counted.In the issue i had written whatsapp, fb and insta, i am still considering twitter and not considering linkedin.

**Comment by rahulkumaran** [comment]
@Anupam-dagar, okie cool! No problem! Just wanted to get it clarified! Thanks though :smile:

**Comment by Anupam-dagar** [comment]
@rahulkumaran no problem, you can contact me for any other doubts too 😄

**Comment by rahulkumaran** [comment]
One small doubt! Can the " everyone " issues on Opencode collaborative still be done?

**Comment by Anupam-dagar** [comment]
No, no more progress can be made now.It will just slow down the evaluation process for us.
You can continue contributing to projects in OpenCode'18 org once we are done with the evaluation and result declaration.

**Comment by rahulkumaran** [comment]
Haha okay! Yeah I get it! You've a hectic task up your sleeves now! All the best for that :P

**Comment by rahulkumaran** [comment]
Also, when would the personal project scores be decided? How would we get it to know about it? :)

**Comment by Anupam-dagar** [comment]
Thanx 😄 
For the personal project, I assume that you have included 50 points for it as of now.Extra points if given will be updated by us in json itself.

**Comment by rahulkumaran** [comment]
Ohh nope, I haven't added that yet! Should I send in another PR wherein I add that issue and 50 points to that?

**Pull request merged**
