### PR TITLE
Games appear in popup

### LINKED ISSUE #360: Make Games appear as a pop up screen inside the webiste
You can use something like Iframe or whatever you like

### PR DESCRIPTION
**Pull request by AK-007**
Fixes #360 

Changes proposed in this pull request:
- made games appear in popup
- used ajax to achieve the same

Link : https://ak-007.github.io/OpenCode-Collaborative/

### CODE REVIEW

**Comment by AK-007** [comment]
@gauthamzz Plz review.Its works fine now.

**Comment by gauthamzz** [comment]
Fix merge conflicts and codacy check, then ask for review

**Comment by AK-007** [comment]
@gauthamzz codacy check passed

**Comment by AK-007** [comment]
@gauthamzz How can I solve "Expected method shorthand. (object-shorthand)" for success function call in ajax?

**Comment by gauthamzz** [comment]
https://api.jquery.com/category/ajax/shorthand-methods/

**Comment by AK-007** [comment]
@gauthamzz Plz review.

**Pull request merged**
