### PR TITLE
Center contents of site.

### LINKED ISSUE #289: Fix alignment
Make it centered
screenshot from 2018-01-14 14-59-05

### PR DESCRIPTION
**Pull request by Ace-Bansal**
Fixes #289

[link](https://ace-bansal.github.io/OpenCode-Collaborative/)

### CODE REVIEW

**Comment by aswanthkoleri** [comment]
@Ace-Bansal Its not exactly center.Use margin : auto ; for containers .

**Comment by Ace-Bansal** [comment]
@aswanthkoleri I had tried that approach initially but it doesn't seem to work here somehow. I'll tweak the vh values a little. I guessing shifting it a bit towards the right will do the trick.

**Comment by Ace-Bansal** [comment]
@aswanthkoleri Have a look now. What I've done is, say the screen width is 100cm and the width of the scrollbar is 10cm, then I've centred the contents of the website over the remaining 90cm instead of the whole 100cm.

**Comment by aswanthkoleri** [comment]
screenshot from 2018-01-20 13-58-33
It doesn't look like it is in the center.Just try to figure out the container holding these sections.And give `margin : auto; ` to them all.Otherwise, by manually adjusting them to the center will create various other problems.For example, If the screen size changes then it will not be centered properly.

**Comment by Anupam-dagar** [comment]
are we using bootstrap grid? if not then why :/
Create a grid, it will automatically make things easier.

**Comment by aswinzz** [comment]
deepinscreenshot_20180121000929

**Comment by Ace-Bansal** [comment]
@Anupam-dagar @aswanthkoleri @aswinzz There was as extraneous row that was causing problems in all the sections. I removed that and gave the divs a text-align center. The cards are centered at all the sizes now.
screenshot 42
screenshot 43

P.S. @aswanthkoleri The margin:auto method wasn't working no matter what I try. Maybe it has something to do with the structure of the code.
P.P.S @Anupam-dagar I couldn't find the resources to implement a grid when a script fetches data and creates cards. Actually I didn't know what I was looking for :p. Would be really helpful if you could direct me to some resources for future use :)

**Comment by Anupam-dagar** [comment]
@Ace-Bansal LGTM 👍

**Pull request merged**
