### PR TITLE
adding cards for game

### PR DESCRIPTION
**Pull request by ananya-agrawal**
Fixes #

Changes proposed in this pull request:
-

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
pls guide me further

**Comment by aswanthkoleri** [comment]
@ananya-agrawal Provide live link

**Comment by ananya-agrawal** [comment]
https://ananya-agrawal.github.io/OpenCode-Collaborative/

**Comment by aswinzz** [comment]
it is not working @ananya-agrawal !

**Comment by Anupam-dagar** [comment]
duplicate closing

**Pull request closed without merging**
