### PR TITLE
Add Yash Agarwal to contestants

### LINKED ISSUE #1: Add yourself to the participants list
Star this repo and everyother repo in opencode for the pull request to be merged :wink:
Go through the readme for guidlines

Staring is to ensure that you saw all the projects in opencode.

### PR DESCRIPTION
**Pull request by yash-agarwal17**
Fixes #1

### CODE REVIEW

**Comment by aswanthkoleri** [comment]
@yash-agarwal17 Fix conflicts

**Comment by yash-agarwal17** [comment]
@aswanthkoleri resolved merge conflicts

**Comment by Anupam-dagar** [comment]
@yash-agarwal17 still there are conflicts

**Comment by gauthamzz** [comment]
inactive

**Pull request closed without merging**
