### PR TITLE
Fixed issue #268

### LINKED ISSUE #268: Link star and fork to the github repo
Only for new commers. To start off with opencode

### PR DESCRIPTION
**Pull request by shivhek25**
Fixes #268

Changes proposed in this pull request:
- Links star and fork on top corner to GitHub repo.

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
May i see live link please?

**Comment by shivhek25** [comment]
How do I provide a live link ? Will a screenshot do ?

**Comment by pradeepgangwar** [comment]
@shivhek25 enable gh-pages from your forked repo settings. A link will be generated. Paste that here.

**Comment by shivhek25** [comment]
That helped. Thank you :) 
Here's the link :
https://shivhek25.github.io/OpenCode-Collaborative/

**Comment by shivhek25** [comment]
I'm not quite sure what that means

**Comment by pradeepgangwar** [comment]
Looks good to me.

**Pull request merged**
