### PR TITLE
Adding a new project and mentor

### PR DESCRIPTION
**Pull request by reverie-ss**
New mentor and new project has been added
Project Addy-Android was not added after submitting the form.

### CODE REVIEW

**Comment by gauthamzz** [comment]
Both your addy projects lack issues, add 7-8 issues and comment. we will add.

**Comment by reverie-ss** [comment]
@gauthamzz Thank you for consideration!
I have added a few issues.
Few other issues were also tagged with opencode18 but it was closed before i could send a PR here

**Comment by gauthamzz** [comment]
looks good , if you fix the merge confilcts . will merge asap.

**Comment by gauthamzz** [comment]
btw can you add some more issues in addy react native as well.

**Comment by reverie-ss** [comment]
@gauthamzz
 I have resolved the conflict.
addy-react-native is mentored by @yashovardhanagrawal , i'll ask him to add some issues!

**Pull request merged**
