### PR TITLE
rectified erros in scores.json and contestants.json

### LINKED ISSUE #435: Fix the Mentors,Participants and Games section ASAP
The above mentioned sections are not loading and needs to fixed urgently.You can check the previous PR's to know what is the problem.

### PR DESCRIPTION
**Pull request by Jigar3**
Fixes #435 #433

### CODE REVIEW

**Comment by gauthamzz** [comment]
deepinscreenshot_select-area_20180128144547

**Comment by Jigar3** [comment]
Is it correct?

**Comment by gauthamzz** [comment]
Names are repeating :/

**Comment by Jigar3** [comment]
@gauthamzz please review

**Pull request merged**
