### PR TITLE
Solved issue#380

### LINKED ISSUE #380: Change the color scheme of issues section
deepinscreenshot_20180121221825
Remove the gradient from the issues section.
NOTE: the color scheme of only the issues section should be changed! .

### PR DESCRIPTION
**Pull request by shivhek25**
Fixes #380 

Changes proposed in this pull request:
- Removed gradient in issues section.

### CODE REVIEW

**Comment by shivhek25** [comment]
The live link is : https://shivhek25.github.io/OpenCode-Collaborative/

**Comment by aswinzz** [comment]
@shivhek25  the new color also looks wierd

**Comment by shivhek25** [comment]
What colour should I put in ?

**Comment by pradeepgangwar** [comment]
@shivhek25 Anything that makes text readable without difficulty. But current color is a bad choice.
screenshot-2018-1-23 opencode

**Comment by shivhek25** [comment]
Is this alright now ?
@aswinzz @pradeepgangwar

**Comment by pradeepgangwar** [comment]
screenshot-2018-1-24 opencode

According to me, if text color can be changed to black it would be good and will be more readable. Also resolve merge conflicts.
@aswinzz ur views?

**Comment by shivhek25** [comment]
screen shot 2018-01-24 at 10 55 52 pm

It's black on my browser.

**Comment by shivhek25** [comment]
Fixed conflicts. @pradeepgangwar

**Comment by pradeepgangwar** [comment]
Are you updating your score in this PR only? And also which browser you are using? I am on Firefox, can you try fixing color on Firefox, if that is not possible, it's ok, leave that.

**Comment by shivhek25** [comment]
Okay. :)

**Comment by shivhek25** [comment]
Is this PR alright to be merged ? Other PRs being merged is creating conflicts regularly now :( 
@pradeepgangwar @aswinzz

**Comment by aswinzz** [comment]
@shivhek25  the text is not readable. change the text color or try some other bg color

**Comment by gauthamzz** [comment]
Just shite bg with black text will be fine.  I cant also read anything .

**Comment by shivhek25** [comment]
I changed it to white. Please check now. @pradeepgangwar @gauthamzz @aswinzz

**Comment by gauthamzz** [comment]
fix the merge conflicts asap

**Comment by shivhek25** [comment]
Please check @gauthamzz @aswinzz @pradeepgangwar

**Comment by gauthamzz** [comment]
dude the text is too light,cant see anything. Just make it visible.

**Comment by shivhek25** [comment]
Please check. @aswinzz @gauthamzz @pradeepgangwar

**Comment by gauthamzz** [comment]
deepinscreenshot_select-area_20180131140246
this is weird

**Comment by shivhek25** [comment]
What exactly is weird ? @gauthamzz

**Comment by Anupam-dagar** [comment]
Yeah that red border only

**Comment by shivhek25** [comment]
Done.

**Comment by shivhek25** [comment]
@gauthamzz @aswinzz @pradeepgangwar @Anupam-dagar Could any of you kindly check the updated PR please ?

**Comment by gauthamzz** [comment]
Congrats 😄

**Comment by shivhek25** [comment]
Thank you.

**Pull request merged**
