### PR TITLE
Hide navbar on landing page.

### LINKED ISSUE #342: Make the navbar hidden in the landing page

### PR DESCRIPTION
**Pull request by Ace-Bansal**
Fixes #342

[link](https://ace-bansal.github.io/OpenCode-Collaborative/)

### CODE REVIEW

**Comment by aswanthkoleri** [comment]
screenshot from 2018-01-20 02-05-32
The Stars and Forks are not being displayed.Fix it.Otherwise LGTM ! :+1:

**Comment by Ace-Bansal** [comment]
Actually the stars and forks aren't being shown in the original site either!

**Comment by aswanthkoleri** [comment]
@Ace-Bansal Yeps So it's not the probelm with your PR. It is a new issue now.I guess you work is fine here. LGTM :+1:

**Comment by Anupam-dagar** [comment]
It works fine but I didn't like the performance though, the animation is not smooth, it's jerky. @Ace-Bansal I implemented this in opencode18 website https://opencode18.github.io, consider taking a look at it.

**Comment by Ace-Bansal** [comment]
@Anupam-dagar On it

**Comment by Ace-Bansal** [comment]
@Anupam-dagar The navbar fades in now instead of appearing abruptly. Have a look please.

**Comment by Anupam-dagar** [comment]
@Ace-Bansal nice, LGTM :+1:

**Pull request merged**
