### PR TITLE
removed gradient on hovering the social icons

### PR DESCRIPTION
**Pull request by pranjalg2308**
Fixes #

Changes proposed in this pull request:
-

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@pranjalg2308 Please add reference to issue it fixes and also add a live link.

**Comment by pranjalg2308** [comment]
Issue#255

**Comment by pradeepgangwar** [comment]
live link?

**Comment by pranjalg2308** [comment]
https://github.com/opencode18/OpenCode-Collaborative/issues/255

**Comment by pranjalg2308** [comment]
what is live link??

**Comment by pradeepgangwar** [comment]
enable gh-pages from your fork and paste the website link. This will help us see the changes u made.

**Comment by Anupam-dagar** [comment]
resolve conflicts too

**Comment by pranjalg2308** [comment]
conflicts resolved

**Comment by aswinzz** [comment]
No files changed !!

**Pull request closed without merging**
