### PR TITLE
FB page Like Button Created

### LINKED ISSUE #162: Add facebook page like button

### PR DESCRIPTION
**Pull request by abhishhh1**
Fixes #162

Changes proposed in this pull request:
-Link-https://abhishhh1.github.io/OpenCode-Collaborative/

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@abhishhh1 Height of navbar has increased too much than it is now. Can you fix it?

**Comment by abhishhh1** [comment]
check it again is it okay now?

**Comment by pradeepgangwar** [comment]
screenshot-2018-1-14 opencode
 No still a major difference is there.

**Comment by abhishhh1** [comment]
okay I'll fix give me some time

**Comment by aswinzz** [comment]
the alignment of the cards has also changed
screenshot from 2018-01-14 14-59-05

**Comment by abhishhh1** [comment]
Wait, I m fixing

**Comment by abhishhh1** [comment]
You created a new issue to fix alignment so can I leave it now? As I,ve created fb page like button in navbar.

**Comment by Anupam-dagar** [comment]
LGTM :+1: @pradeepgangwar ?
@abhishhh1 resolve conflicts

**Comment by pradeepgangwar** [comment]
@abhishhh1 u din't want to do this?

**Pull request closed without merging**
