### PR TITLE
Fixes #102 Added Projects

### LINKED ISSUE #102: Add card for projects
Add card in same way as persons name .
and a json should be created for projects.
take projects list.
Comment on issue #31 along witht the screenshot to get your marks verified. :smile:

### PR DESCRIPTION
**Pull request by Tlazypanda**
Added project js and json file.Left the image url empty for now in the json file.Also added navbar link for the projects section.After merging kindly change the js file link to the opencode master branch from my username.Not sure about the gradient in the card(doesn't look pretty i know).
https://tlazypanda.github.io/OpenCode-Collaborative/
For the preview.Kindly let me know if any changes are required.

### CODE REVIEW

**Comment by Tlazypanda** [comment]
I know the css sucks.I have left it right now because I dont have image for the projects.Should I work on it as a new issue?

**Comment by pradeepgangwar** [comment]
This does not look impressive. Try modifying it.

**Comment by Tlazypanda** [comment]
Ohkay sir! On it.

**Comment by Anupam-dagar** [comment]
@Tlazypanda the gradient is not fitting the box properly, its going out.

**Comment by Tlazypanda** [comment]
screenshot

The gradient issue is fixed now.But I have seeked the expert Aayush Joglekar on beautifying the css of the cards.Final pull request would be made by him.So points de dena usse xD.

**Comment by aayushjoglekar** [comment]
@Anupam-dagar Since she has requested, I have resolved the CSS problem issue #102 and I am making another PR.

**Comment by pradeepgangwar** [comment]
closing this as other PR got merged.

**Pull request closed without merging**
