### PR TITLE
Issue #396 : Spacing Reduced

### LINKED ISSUE #396: Decrease the spacing in the image
deepinscreenshot_select-area_20180123025117

### PR DESCRIPTION
**Pull request by aayushjoglekar**
@gauthamzz 

Fixed #396 

l6

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
live link?

**Comment by aayushjoglekar** [comment]
@Anupam-dagar 

https://aayushjoglekar.github.io/OpenCode-Collaborative

**Comment by Anupam-dagar** [comment]
consider re-forking your repo

**Comment by gauthamzz** [comment]
Syc the branch , use branches . 
Use master branch for syc and when solving an issue make 
Git checkout -b someissue 
Push from this branch 

You can do multiple issues this way 
And syc master of your fork always with master of remote branch . Quick google search will give you a link to do that

**Pull request merged**
