### PR TITLE
Added watch trailer option with video popup

### LINKED ISSUE #163: Add watch trailer on nav bar and pop up for youtube video

### PR DESCRIPTION
**Pull request by arpitmisraw**
Fixes #163 

Changes proposed in this pull request:
1. Added trailer option in the header.
2. Trailer option makes the youtube video popup.
3. User can click anywhere else to exit.

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
Live link?

**Comment by arpitmisraw** [comment]
I'm having some problems. It seems to work fine on my system, but the live link shows some problem. What should I do?

**Comment by arpitmisraw** [comment]
I's working now. Here's the link-
 https://arpitmisraw.github.io/OpenCode-Collaborative/

**Comment by pradeepgangwar** [comment]
screenshot from 2018-01-13 19-15-15

Link color does not mach other link colors, Please change.

**Pull request merged**
