### PR TITLE
Update blog section

### LINKED ISSUE #482: update blog section
blog section on website don't have all the blogs written by participants.Update it.

### PR DESCRIPTION
**Pull request by Ace-Bansal**
Fixes #482

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@Ace-Bansal conflicts

**Comment by Ace-Bansal** [comment]
@Anupam-dagar done

**Comment by Anupam-dagar** [comment]
@Ace-Bansal live link?
Don't forget to put live link for front end changes :stuck_out_tongue:

**Comment by Ace-Bansal** [comment]
@Anupam-dagar The new blogs aren't rendering on my link even though I've updated the blogs.json correctly

**Pull request merged**
