### PR TITLE
Solution for Issue #162

### PR DESCRIPTION
**Pull request by abhishhh1**
#162

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
Fix conflicts, Provide live link and mention issue in description not the title of the PR.

**Comment by pradeepgangwar** [comment]
@abhishhh1 Please provide live link. And also reference issue in this PR.

**Comment by abhishhh1** [comment]
<li>Link - [https://abhishhh1.github.io/OpenCode-Collaborative/ ](url)

**Comment by gauthamzz** [comment]
It should be in the nav bar
It doesnt look working to me.

**Comment by abhishhh1** [comment]
it is working....okay i m going to put in navbar

**Comment by shivhek25** [comment]
Has this issue been solved ? If not, I would like to work on it.

**Comment by gauthamzz** [comment]
last activity is 5 hours ago. If is only more than 24 hours only you can claim it @shivhek25

**Pull request closed without merging**
