### PR TITLE
fixes #29 Adding logos

### LINKED ISSUE #29: Add FOSSIIITA,IIITA and GeekHaven logo.
Add the following logos on the right side of the footer.Similar,to that seen in the Main page : [OpenCode](https://opencode18.github.io)

### PR DESCRIPTION
**Pull request by Tlazypanda**

### CODE REVIEW

**Comment by aswanthkoleri** [comment]
Provide live link

**Comment by Tlazypanda** [comment]
screenshot
Is this alright?

**Comment by Tlazypanda** [comment]
I am not exactly sure on how to deploy active gh-link.Would the screenshot do?

**Comment by aswinzz** [comment]
keep that logo in the left corner

**Comment by aswinzz** [comment]
@Tlazypanda go to settings and there will be an option for gh-pages turn it on and you will get the url.

**Comment by Tlazypanda** [comment]
ohkay cool! Thanks sir I have made a new pr for the same.Kindly review it.

**Pull request closed without merging**
