### PR TITLE
Update index.html Fixes #2

### LINKED ISSUE #2: change title,heading and footer to opencode

### PR DESCRIPTION
**Pull request by Tlazypanda**
changes title,heading and footer text to opencode.

### CODE REVIEW

**Comment by Tlazypanda** [comment]
Is there anything else that needs to be done for this specific issue? I am not sure if that is all that's reqd.

**Comment by Jigar3** [comment]
@Tlazypanda  Please provide a gh-page deployment link

**Comment by aswinzz** [comment]
please do not take up the issue without commenting on the issue that you would like to work on it! Another participant was working on it and we don't want two people working on same issue.
Please read the guidlines once!

**Comment by Tlazypanda** [comment]
Oh! sorry wasn't aware of the same.Will make sure to comment before taking up a new issue.

**Pull request closed without merging**
