### PR TITLE
Issue 27 Smooth rotation of tile fixed

### LINKED ISSUE #235: Fix the flip card animation.
The flip card does'nt rotate smoothly after clicking it once.

### PR DESCRIPTION
**Pull request by brain-sick**
Fixes #235 

Changes proposed in this pull request:
-modified some classes in style.css

### CODE REVIEW

**Comment by aswinzz** [comment]
provide the live link!

**Comment by pradeepgangwar** [comment]
Also update description to depict issue it is related to.

**Comment by brain-sick** [comment]
live link- 
https://brain-sick.github.io/OpenCode-Collaborative/

**Comment by pradeepgangwar** [comment]
Looks Good :+1:

**Pull request merged**
