### PR TITLE
Fixed issue #232

### LINKED ISSUE #232: change countdown timer color to gradient

### PR DESCRIPTION
**Pull request by prathamprakash29**
[live link](https://prathamprakash29.github.io/OpenCode-Collaborative/)

Closes #232

### CODE REVIEW

**Comment by aswinzz** [comment]
try some gradient instead of white

**Comment by prathamprakash29** [comment]
@aswinzz check again.. is this fine?

**Comment by Anupam-dagar** [comment]
make the outer box (light green) color change to gradient as used in the webstie and the inner box color to white.Numbers should be black

**Comment by prathamprakash29** [comment]
@Anupam-dagar I have updated it.. check the live link

**Comment by prathamprakash29** [comment]
@Anupam-dagar fixed it.. check the live link

**Pull request merged**
